### ISSUE TITLE
xinputStick hook outputs wrong info

### ISSUE THREAD

**Issue by adamnejm** [mitterdoo/garrysmod-xinput#2]
Everything here have only been tested in Starfall.
First of all, I found out that parameters are in wrong order
Docs: `id, stick, x, y, when`
Reality: `id, x, y, stick, when`
I'm using the second order.

1. When I move stick to the left, X will go from `>65000 to 32769` when, not from `0 to -32768`
2. When stick's position Y is below 0, X will always output value of `65535`

This only happens when using hook, `xinput.getStick( id, stick )` function outputs correct values.

On the video graphics represent values returned by `getStick` function and below are the values passed to `xinputStick` hook.
Orange - Stick to the left side (point 1)
Red - Stick on the bottom (point 2)
https://media.adamnejm.com/2019/12/BGiwL.mp4

**Comment by adamnejm** [comment]
Forgot to mention:
I'm using Steam Controller
This affect both the stick and the touchpad

**Comment by Thomasims** [comment]
I noticed that as well a few weeks ago and made PR #1 to fix it. I'm still waiting for @mitterdoo to review and approve.

**Comment by mitterdoo** [comment]
I haven't checked GitHub in a while, pardon the wait. I'll look further into this tomorrow

**Comment by mitterdoo** [comment]
Fixed by 717d237d06b0e4297dd4b6ad5219caeb4636e0a1
